// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $add from "./routes/add.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $buscar from "./routes/buscar.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Buscar from "./islands/Buscar.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $Superheroe from "./islands/Superheroe.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/add.tsx": $add,
    "./routes/api/joke.ts": $api_joke,
    "./routes/buscar.tsx": $buscar,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Buscar.tsx": $Buscar,
    "./islands/Form.tsx": $Form,
    "./islands/Superheroe.tsx": $Superheroe,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
